### ISSUE TITLE
Labeling example dataset error

### ISSUE THREAD

**Issue by agr78** [mui-neuro/swi-cnn#3]
I ran the preprocessing command with no trouble but after running `swi-cnn.py -s example_subject --label_regions`, I encounter an error:

`Traceback (most recent call last):
  File "/home/swi-cnn/swi-cnn.py", line 781, in <module>
    unite=True)
  File "/home/swi-cnn/utils.py", line 1153, in label_regions
    patch = ants.image_read(fname)
  File "/home/anaconda3/envs/swi-cnn/lib/python3.7/site-packages/ants/core/ants_image_io.py", line 515, in image_read
    raise ValueError("File %s does not exist!" % filename)
ValueError: File /home/swi-cnn/labels/patches/unetpp/sigmoid/rn_r/example_subject.nii.gz does not exist!`

**Comment by vbeliveau** [comment]
Thanks for reporting this. The `--label_patches` was missing from the instructions and is required to run the patch extraction step which needs to be performed before the labeling.

**Comment by agr78** [comment]
Great, thanks. I can generate a segmentation for `example_subject` now. When I try a NIFTI from my own dataset, the same command with `--label_patches` and `--label_regions` completes nearly instantly and doesn't create patches or segmentations. Any recommendations? Shall I open a new issue for this?

**Comment by vbeliveau** [comment]
Yes please, this seems to be a different issue. Also, please provide the full command you're using and the output.
