### ISSUE TITLE
Output segmentation dimensions

### ISSUE THREAD

**Issue by agr78** [mui-neuro/swi-cnn#5]
Is there an way to output the segmentation with the same dimensions as the original input image?

**Comment by vbeliveau** [comment]
The current approach was designed to handle isotropic images. If your image has isotropic voxels, then you can specify the resolution using the --full_resolution flag. Another option, would be to resample the output segmentation to your exact target dimensions.

**Comment by agr78** [comment]
Got it, I added a registration between `data` and `data_iso` to get the transform to be applied to the combined labels.
