### ISSUE TITLE
preallocate_segmentation code missing

### ISSUE THREAD

**Issue by dohyun-as** [mui-neuro/swi-cnn#6]
Hi!

I'm trying to train new models. But I can't find `preallocate_segmentation`  code in swi-cnn.py. Can I get preallocate_segmentation code?

Thanks!

**Comment by vbeliveau** [comment]
Hi there! The `preallocate_segmentation` was deprecated in favor of `preallocate_mixed_segmentation` which handles the creation of images with both single and multiple labels. The flag `preallocate_segmentation` will be removed.

**Comment by dohyun-as** [comment]
Thank you for your reply!
