### ISSUE TITLE
Question about `--patch_cv` and `--segmentation_cv` options.

### ISSUE THREAD

**Issue by dohyun-as** [mui-neuro/swi-cnn#7]
Hi,
I have a question that arose during the process of training a new model.

Where are the models created with the options `--patch_cv` and `--segmentation_cv` used? Is that model not used? Can I train the model using only `--final`?

And what should I do when facing slow convergence, causing the model not to be saved?

**Comment by vbeliveau** [comment]
@DH1929ds sorry for not addressing this sooner, but, in case this might be useful for anyone else, `--path_cv` and `--segmentation_cv` are used to perform the cross-validation of the patch and segmentation models. The models will be stored in `models/<patch or region>/<model>/n_fold-<fold>`. To get the final models trained using all the data you would use `--patch_final` and `--segmentation_final`.

**Comment by dohyun-as** [comment]
Hi,

Thanks for your clear reply!
